language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy
  - pypy3
install:
  - pip install flake8==2.1.0 pep8==1.5.6
  - python setup.py install
  - pip list
  - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then flake8 --version; fi
script:
  - python setup.py test -q
  - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then flake8 pyflakes setup.py; fi
  - echo python -c "import pyflakes.api; pyflakes.api.checkRecursive('$VIRTUAL_ENV', None);" > pyflakes.out 2>&1
  - echo "pyflakes $VIRTUAL_ENV results" && echo -en 'travis_fold:start:script.1\\r'
  - cat pyflakes.out
  - echo -en 'travis_fold:end:script.1\\r'
sudo: false
