language: python
python:
  - nightly
install:
  - pip install flake8==2.1.0 pep8==1.5.6
  - python setup.py install
  - pip list
  - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then flake8 --version; fi
script:
  - python setup.py test -vv
  - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then flake8 pyflakes setup.py; fi
sudo: false
