sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy
  - pypy3
addons:
  apt:
    packages:
      - bar
install:
  - pip install flake8==2.1.0 pep8==1.5.6
  - python setup.py install
  - pip list
  - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then flake8 --version; fi
script:
  - python setup.py test -q
  - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then flake8 pyflakes setup.py; fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.5" ]; then
      echo "Running 'pyflakes '"$VIRTUAL_ENV/lib/python*"' results" && echo -en 'travis_fold:start:script.1\\r' ;
      python -c "import pyflakes.api; pyflakes.api.checkRecursive('$VIRTUAL_ENV/lib/python*', None);" 2>&1 | bar > pyflakes.log ;
      echo -en 'travis_fold:end:script.1\\r' ;
    fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.5" ]; then tail -100 pyflakes.log; fi
after_script:
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.5" ]; then
      echo "'pyflakes '"$VIRTUAL_ENV/lib/python*"' results" && echo -en 'travis_fold:start:after_script.1\\r' ;
      cat pyflakes.out ;
      echo -en 'travis_fold:end:after_script.1\\r' ;
    fi
