language: python
cache: pip
python:
  - pypy3.5  # 3.5.3 (PyPy 5.10.1)
  - pypy3.5-5.8.0
  - pypy-5.3
  - pypy-5.4
  - pypy-5.5
  - pypy-5.6
  - pypy-5.7
  - pypy-5.7.1
install:
  - pip install --upgrade .
  - pip list
script:
  - python setup.py test -q
  - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then pip install flake8==2.1.0 pep8==1.5.6 && flake8 --version && flake8 pyflakes setup.py; fi
sudo: false
