language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy
  - pypy-5.3
  - pypy3
  - pypy3.3-5.2-alpha1
install:
  - pip install -U "pip<8" setuptools
  - pip install tox tox-travis
script:
  - tox
sudo: false
